### ISSUE TITLE
OBVIOUSLY WRONG DESCRIPTION IS WRONG

### ISSUE THREAD

**Issue by williammartin** [teddyking/dependency-action#1]
https://github.com/teddyking/dependency-action/blob/0aaafb8bedba37deb78eaec0158881933ed039be/acceptance/acceptance_test.go#L84

`that does point` -> `that does not point`

Get with the program.

**Comment by teddyking** [comment]
Ah how very embarrassing. Thanks for pointing that out, would you be willing to submit a PR?

**Comment by williammartin** [comment]
No

**Comment by williammartin** [comment]
Honestly, you OSS maintainers are good for nothing. Just do work for me.

**Comment by teddyking** [comment]
OK Boomer
